replicaCount: 1

auth:
  rbac:
    create: false
  token:
    enabled: false

image:
  registry: docker.io
  repository: bitnamilegacy/etcd
  tag: 3.6.4-debian-12-r3

service:
  type: ClusterIP

persistence:
  enabled: true
  # UPDATE: Match the StorageClass name created by your NFS-infra
  storageClass: "nfs-client-etcd"   
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # NOTE: nfsPath is removed because the Provisioner handles the 
  # directory creation automatically based on its own config.

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoCompactionMode: revision
autoCompactionRetention: "1000"

metrics:
  enabled: true


preUpgradeJob:
  enabled: false